### ISSUE TITLE
Error in git-shuffle and other commands

### ISSUE THREAD

**Issue by rec** [rec/gitz#156]
$ git shuffle abc -s "New git-restore" -v
    git shuffle abc -s "New git-restore" -v
    $ git diff-index --quiet HEAD --
    $ git rev-parse HEAD~0
    > c8a3f213ee4de91005543478425f689d10da8113
    $ git show-branch --no-name 0
    Traceback (most recent call last):
      File "/code/gitz/gitz/program/program.py", line 35, in start
        main()
      File "/code/gitz/git-shuffle", line 78, in git_shuffle
        id_msgs = functions.commit_messages(count)
      File "/code/gitz/gitz/git/functions.py", line 38, in commit_messages
        return [commit_message(i) for i in range(count)]
      File "/code/gitz/gitz/git/functions.py", line 38, in <listcomp>
        return [commit_message(i) for i in range(count)]
      File "/code/gitz/gitz/git/functions.py", line 34, in commit_message
        return commit_id(name, short), message(name)
      File "/code/gitz/gitz/git/functions.py", line 30, in message
        return GIT.show_branch('--no-name', name, info=True)[0]
      File "/code/gitz/gitz/program/runner.py", line 56, in __call__
        return self.runner('git', *cmd, **kwds)
      File "/code/gitz/gitz/program/runner.py", line 37, in __call__
        run_proc.run_proc(cmd, kwds, out, err)
      File "/code/gitz/gitz/program/run_proc.py", line 17, in run_proc
        p = subprocess.Popen(cmd, **kwds)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1275, in _execute_child
        restore_signals, start_new_session, preexec_fn)
    TypeError: expected str, bytes or os.PathLike object, not int

    ERROR: git-shuffle: TypeError: expected str, bytes or os.PathLike object, not int
    [gitz] (restore) tom@bantam:/code/gitz$

**Comment by rec** [comment]
Seems to be a recent reversion in the last commit!

**Comment by rec** [comment]
Fixed!
