### ISSUE TITLE
Syntax errors!

### ISSUE THREAD

**Issue by rec** [rec/gitz#165]
$ git rename -f restore master

    Traceback (most recent call last):
      File "/code/gitz/git-rename", line 2, in <module>
        from gitz.git import mover
      File "/code/gitz/gitz/git/mover.py", line 99
        GIT.push(*fl, '--set-upstream', self.origin, self.target)
                             ^
    SyntaxError: only named arguments may follow *expression

1. How could I have a syntax error when I even have a unit test for it?

2. It shouldn't have gotten there - it should have disallowed `master` as a protected branch

**Comment by rec** [comment]
What the?  I'm getting this here:

    [gitz] (master) tom@bantam:/code/gitz$ git stripe
      File "/code/gitz/git-stripe", line 128
        GIT.push(*force, remote, refspec)
                                    ^
    SyntaxError: only named arguments may follow *expression
