### ISSUE TITLE
git-delete crash

### ISSUE THREAD

**Issue by rec** [rec/gitz#27]
My guess - it was a file with local branch that hadn't got an upstream.

    Traceback (most recent call last):
      File "/code/gitz/git-delete", line 72, in <module>
        git_delete()
      File "/code/gitz/git-delete", line 59, in git_delete
        total_count = git_functions.delete(args.target, PROGRAM, remotes)
      File "/code/gitz/gitz/git_functions.py", line 74, in delete
        git.push(remote, '--delete', target)
      File "/code/gitz/gitz/git.py", line 24, in git
        return util.run('git', *cmd, verbose=self.verbose, **kwds)
      File "/code/gitz/gitz/util.py", line 22, in run
        lines = subprocess.check_output(cmd, **kwds).splitlines()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'git push testing --delete x-sand-3' returned non-zero exit status 1.

**Comment by rec** [comment]
This is probably closed by fd7f8f59293193e04c6a61d2fbf2bb21f8901302 - I'll reopen if later testing reveals it isn't.

**Comment by rec** [comment]
This is now occurring because I have two different remotes pointing to the same repo! :-)

This will be rare, but we can't disallow it.
